deployment_name: demo-example
version_name: v1
language: python3.8
instance_type: 256mb
minimum_instances: 0
maximum_instances: 1
maximum_idle_time: 1800
request_retention_mode: full
request_retention_time: 3600
maximum_queue_size_express: 100
maximum_queue_size_batch: 100000
